name: CI Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kodun kendisi
      - name: Checkout repository
        uses: actions/checkout@v5

      # JDK kurulumu
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      # Gradle setup
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Debug APK build (keyless)
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # Release APK build (debug key ile)
      - name: Build release APK with debug key
        run: ./gradlew assembleRelease \
          -Psigning.storeFile=$HOME/.android/debug.keystore \
          -Psigning.storePassword=android \
          -Psigning.keyAlias=androiddebugkey \
          -Psigning.keyPassword=android

      # APK'yı artifact olarak sakla
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: aniyomi-apks
          path: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/release/*.apk
          retention-days: 7
